[package]
name = "tracing-fastly"
version = "0.1.0"
edition = "2024"

[dependencies]
fastly = "0.13.0"
serde = "1.0"
serde_json = "1.0.137"
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["registry"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.21.0"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["fmt", "env-filter"] }
